#!/usr/bin/env bash

CMD="$@"

START=$(date +%s)
"$@"
END=$(date +%s)
SECS=$((END-START))
TM=$(printf '%dm%ds\n' $(($SECS%3600/60)) $(($SECS%60)))

if [ $? -eq 0 ]; then
    echo SUCCESS
    notifyme Success "$CMD"$'\n'"(${TM})" > /dev/null 2>&1
else
    echo FAILED
    notifyme Failed "$CMD"$'\n'"(${TM})" > /dev/null 2>&1
fi
